/* verilator lint_off UNUSED */
/* verilator lint_off WIDTH */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off STMTDLY */
/* verilator lint_off UNDRIVEN */
// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gsm_mult_r (
        a,
        b,
        ap_return
);

parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv31_4000 = 31'b100000000000000;

input  [15:0] a;
input  [15:0] b;
output  [15:0] ap_return;

wire  signed [30:0] grp_fu_43_p3;
wire   [15:0] grp_fu_43_p1;
wire   [15:0] grp_fu_43_p2;
wire   [30:0] grp_fu_43_p10;

Gsm_LPC_Analysis_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
Gsm_LPC_Analysis_bkb_U2(
    .din0(a),
    .din1(grp_fu_43_p1),
    .din2(grp_fu_43_p2),
    .dout(grp_fu_43_p3)
);

assign ap_return = {{grp_fu_43_p3[ap_const_lv32_1E : ap_const_lv32_F]}};

assign grp_fu_43_p1 = grp_fu_43_p10;

assign grp_fu_43_p10 = b;

assign grp_fu_43_p2 = ap_const_lv31_4000;

endmodule //gsm_mult_r
