/* verilator lint_off UNUSED */
/* verilator lint_off WIDTH */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off STMTDLY */
/* verilator lint_off UNDRIVEN */
// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gsm_abs (
        a,
        ap_return
);

parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv16_8000 = 16'b1000000000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv16_7FFF = 16'b111111111111111;

input  [15:0] a;
output  [15:0] ap_return;

wire   [0:0] tmp_s_fu_28_p2;
wire   [15:0] tmp_5_fu_34_p2;
wire   [0:0] tmp_fu_20_p3;
wire   [15:0] tmp_6_fu_40_p3;

assign ap_return = ((tmp_fu_20_p3[0:0] === 1'b1) ? tmp_6_fu_40_p3 : a);

assign tmp_5_fu_34_p2 = (ap_const_lv16_0 - a);

assign tmp_6_fu_40_p3 = ((tmp_s_fu_28_p2[0:0] === 1'b1) ? ap_const_lv16_7FFF : tmp_5_fu_34_p2);

assign tmp_fu_20_p3 = a[ap_const_lv32_F];

assign tmp_s_fu_28_p2 = ((a == ap_const_lv16_8000) ? 1'b1 : 1'b0);

endmodule //gsm_abs
